chore(install script): update install script #109

diff --git a/.github/workflows/install_script_test.yaml b/.github/workflows/install_script_test.yaml
--- a/.github/workflows/install_script_test.yaml
+++ b/.github/workflows/install_script_test.yaml
@@ -418,90 +418,90 @@ jobs:
 #          printf "${SUCCESSFUL_LOG}"
 #
 
-  wget_on_ubuntu:
-    needs:
-      - setup_matrix_for_ubuntuOS
-    name: Wget on ubuntu
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
-    env:
-      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
-
-    steps:
-      - name: Successful wget download on ubuntu
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            apt update;
-            apt install -y wget;
-            wget -O- ${INSTALLATION_URL} | bash
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -gt 0 ] || exit 1
-          echo "${SUCCESSFUL_LOG}"
-      - name: Failed wget download on ubuntu
-        run: |
-          sudo rm -rf * .??*
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            apt update;
-            wget -O- ${INSTALLATION_URL} | bash
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] || exit 1
-
-  wget_tar_on_ubuntu:
-    name: Wget->tar on ubuntu
-    needs:
-      - setup_matrix_for_ubuntuOS
-      - wget_on_ubuntu
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
-    env:
-      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
-
-    steps:
-      - name: Successful wget download on ubuntu
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            apt update;
-            apt install -y wget tar;
-            wget -O- ${INSTALLATION_URL} | bash
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -gt 0 ] || exit 1
-          printf "${SUCCESSFUL_LOG}"
-
-  wget_unzip_on_ubuntu:
-    name: Wget->unzip on ubuntu
-    needs:
-      - setup_matrix_for_ubuntuOS
-      - wget_on_ubuntu
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
-    env:
-      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
-
-    steps:
-      - name: Successful wget download on ubuntu
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            apt update;
-            apt install -y wget unzip;
-            rm -rf /usr/bin/tar # remove curl
-            wget -O- ${INSTALLATION_URL} | bash
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -gt 0 ] || exit 1
-          printf "${SUCCESSFUL_LOG}"
+#  wget_on_ubuntu:
+#    needs:
+#      - setup_matrix_for_ubuntuOS
+#    name: Wget on ubuntu
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+#    env:
+#      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
+#
+#    steps:
+#      - name: Successful wget download on ubuntu
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            apt update;
+#            apt install -y wget;
+#            wget -O- ${INSTALLATION_URL} | bash
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -gt 0 ] || exit 1
+#          echo "${SUCCESSFUL_LOG}"
+#      - name: Failed wget download on ubuntu
+#        run: |
+#          sudo rm -rf * .??*
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            apt update;
+#            wget -O- ${INSTALLATION_URL} | bash
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] || exit 1
+#
+#  wget_tar_on_ubuntu:
+#    name: Wget->tar on ubuntu
+#    needs:
+#      - setup_matrix_for_ubuntuOS
+#      - wget_on_ubuntu
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+#    env:
+#      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
+#
+#    steps:
+#      - name: Successful wget download on ubuntu
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            apt update;
+#            apt install -y wget tar;
+#            wget -O- ${INSTALLATION_URL} | bash
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -gt 0 ] || exit 1
+#          printf "${SUCCESSFUL_LOG}"
+#
+#  wget_unzip_on_ubuntu:
+#    name: Wget->unzip on ubuntu
+#    needs:
+#      - setup_matrix_for_ubuntuOS
+#      - wget_on_ubuntu
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+#    env:
+#      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
+#
+#    steps:
+#      - name: Successful wget download on ubuntu
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            apt update;
+#            apt install -y wget unzip;
+#            rm -rf /usr/bin/tar # remove curl
+#            wget -O- ${INSTALLATION_URL} | bash
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -gt 0 ] || exit 1
+#          printf "${SUCCESSFUL_LOG}"
