chore(install script): update install script #74

diff --git a/.github/workflows/install_script_test.yaml b/.github/workflows/install_script_test.yaml
--- a/.github/workflows/install_script_test.yaml
+++ b/.github/workflows/install_script_test.yaml
@@ -11,48 +11,50 @@ env:
   SUCCESSFUL_LOG: 'echo "\033[0;32mPASS\033[0m %s\n"'
 
 jobs:
-  curl_download_on_centOS:
-    runs-on: ubuntu-latest
-    name: curl download on CentOS
-    strategy:
-      matrix:
-        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
-    env:
-      CENTOS_VERSION: ${{ matrix.centos }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by curl
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf * .??*
-            curl -fsSL ${INSTALLATION_URL} | bash
-            ls -ahl
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 1
-          echo "${SUCCESSFUL_LOG}"
 
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a failed download by curl
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf * .??*
-            yum remove -y curl
-            curl -fsSL ${INSTALLATION_URL} | bash
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 0
-          echo "${SUCCESSFUL_LOG}"
+#  curl_download_on_centOS:
+#    runs-on: ubuntu-latest
+#    name: curl download on CentOS
+#    strategy:
+#      matrix:
+#        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
+#    env:
+#      CENTOS_VERSION: ${{ matrix.centos }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by curl
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf * .??*
+#            curl -fsSL ${INSTALLATION_URL} | bash
+#            ls -ahl
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 1
+#          echo "${SUCCESSFUL_LOG}"
+#
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a failed download by curl
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf * .??*
+#            yum remove -y curl
+#            curl -fsSL ${INSTALLATION_URL} | bash
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 0
+#          echo "${SUCCESSFUL_LOG}"
+#
 
 #  curl_tar_on_centOS:
 #    needs: curl_download_on_centOS
