chore(install script): update install script #288

diff --git a/.github/workflows/install_script_test.yaml b/.github/workflows/install_script_test.yaml
--- a/.github/workflows/install_script_test.yaml
+++ b/.github/workflows/install_script_test.yaml
@@ -147,9 +147,9 @@ jobs:
         run: |
           docker run -itd -v $PWD:/workdir --name ${CONTAINER_NAME} -w /workdir ${UBUNTU_IMAGE_VERSION}
           docker exec ${CONTAINER_NAME} bash -c "
+            apt install -y curl
             set -e
             export TERM=xterm
-            apt install -y curl
             curl -fsSL ${INSTALLATION_URL} | bash
           "
       - name: Check the installation of dotfiles was successful or not
@@ -159,35 +159,35 @@ jobs:
             apt install -y make
             make check_dotfiles_installed
           "
-  wget_installation_on_ubuntu:
-    needs:
-      - setup_matrix_for_ubuntuOS
-    name: Wget installation on ubuntu
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
-    env:
-      UBUNTU_IMAGE_VERSION: ${{ matrix.image}}
-    steps:
-      - name: Set container name
-        id: vars
-        run: |
-          echo "CONTAINER_NAME=ubuntu" >> $GITHUB_ENV
-      - name: Install dotfiles by wget on ubuntu.
-        run: |
-          docker run -itd -v $PWD:/workdir --name ${CONTAINER_NAME} -w /workdir ${UBUNTU_IMAGE_VERSION}
-          docker exec ${CONTAINER_NAME} bash -c "
-            set -e
-            export TERM=xterm
-            apt install -y wget
-            wget -O- ${INSTALLATION_URL} | bash
-          "
-      - name: Check the installation of dotfiles was successful or not
-        run: |
-          docker exec ${CONTAINER_NAME} bash -c "
-            cd dotfiles
-            apt install -y make
-            make check_dotfiles_installed
-          "
+#  wget_installation_on_ubuntu:
+#    needs:
+#      - setup_matrix_for_ubuntuOS
+#    name: Wget installation on ubuntu
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+#    env:
+#      UBUNTU_IMAGE_VERSION: ${{ matrix.image}}
+#    steps:
+#      - name: Set container name
+#        id: vars
+#        run: |
+#          echo "CONTAINER_NAME=ubuntu" >> $GITHUB_ENV
+#      - name: Install dotfiles by wget on ubuntu.
+#        run: |
+#          docker run -itd -v $PWD:/workdir --name ${CONTAINER_NAME} -w /workdir ${UBUNTU_IMAGE_VERSION}
+#          docker exec ${CONTAINER_NAME} bash -c "
+#            set -e
+#            export TERM=xterm
+#            apt install -y wget
+#            wget -O- ${INSTALLATION_URL} | bash
+#          "
+#      - name: Check the installation of dotfiles was successful or not
+#        run: |
+#          docker exec ${CONTAINER_NAME} bash -c "
+#            cd dotfiles
+#            apt install -y make
+#            make check_dotfiles_installed
+#          "
