chore(install script): update install script #62

diff --git a/.github/workflows/install_script_test.yaml b/.github/workflows/install_script_test.yaml
--- a/.github/workflows/install_script_test.yaml
+++ b/.github/workflows/install_script_test.yaml
@@ -10,146 +10,164 @@ env:
   GIT_VERSION: 'v0.0.45'
 
 jobs:
-  curl_download_on_centOS:
+#  curl_download_on_centOS:
+#    runs-on: ubuntu-latest
+#    name: curl download on CentOS
+#    strategy:
+#      matrix:
+#        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
+#    env:
+#      CENTOS_VERSION: ${{ matrix.centos }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by curl
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf * .??*
+#            curl -fsSL ${INSTALLATION_URL} | sh
+#            ls -ahl
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 1
+#          echo "PASS"
+#
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a failed download by curl
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf * .??*
+#            yum remove -y curl
+#            curl -fsSL ${INSTALLATION_URL} | sh
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 0
+#          echo "PASS"
+#
+#  wget_download_on_centOS:
+#    runs-on: ubuntu-latest
+#    name: wget download on CentOS
+#    strategy:
+#      matrix:
+#        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
+#    env:
+#      CENTOS_VERSION: ${{ matrix.centos }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by wget
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf /usr/bin/curl # remove curl
+#            yum install -y wget
+#            rm -rf * .??*
+#            wget -O- ${INSTALLATION_URL} | sh
+#            ls -ahl
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 1
+#          echo "PASS"
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a failed download by wget
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf /usr/bin/curl # remove curl
+#            command -v "wget"
+#            [ -f /usr/bin/wget ] && rm -f /usr/bin/wget
+#            rm -rf * .??*
+#            wget -O- ${INSTALLATION_URL} | sh
+#            ls -ahl
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] || exit 1
+#          echo "PASS"
+#
+#  git_download_on_centOS:
+#    runs-on: ubuntu-latest
+#    name: wget download on CentOS
+#    strategy:
+#      matrix:
+#        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
+#    env:
+#      CENTOS_VERSION: ${{ matrix.centos }}
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by git
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
+#            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
+#            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
+#            cat /etc/yum.repos.d/CentOS-Base.repo
+#            rm -rf /usr/bin/curl # remove curl
+#            yum install -y git
+#            rm -rf * .??*
+#            git clone --branch ${GIT_VERSION} --single-branch --recurse-submodules ${GIT_REP_URL} && cd dotfiles
+#            ls -ahl
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] && exit 1
+#          echo "PASS"
+#
+#  curl_download_on_macOS_x86:
+#    runs-on: macos-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by curl
+#        run: |
+#          curl -fsSL ${INSTALLATION_URL} | sh
+#
+#  wget_download_on_macOS_x86:
+#    runs-on: macos-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by wget
+#        run: |
+#          wget -O- ${INSTALLATION_URL} | sh
+#  git_download_on_macOS_x86:
+#    runs-on: macos-latest
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#      - name: Asserting the result of a successful download by git
+#        run: |
+#          git clone --branch ${GIT_VERSION} --single-branch --recurse-submodules ${GIT_REP_URL} && cd dotfiles
+
+  curl_download_on_ubuntu:
     runs-on: ubuntu-latest
-    name: curl download on CentOS
     strategy:
       matrix:
-        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
+        image: [ 'node:14', 'node:15' ]
     env:
       CENTOS_VERSION: ${{ matrix.centos }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by curl
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf * .??*
-            curl -fsSL ${INSTALLATION_URL} | sh
-            ls -ahl
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 1
-          echo "PASS"
+    container:
+      image: ${{ matrix.image }} # Specify the Docker image to use
 
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a failed download by curl
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf * .??*
-            yum remove -y curl
-            curl -fsSL ${INSTALLATION_URL} | sh
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 0
-          echo "PASS"
-
-  wget_download_on_centOS:
-    runs-on: ubuntu-latest
-    name: wget download on CentOS
-    strategy:
-      matrix:
-        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
-    env:
-      CENTOS_VERSION: ${{ matrix.centos }}
     steps:
-      - name: Checkout code
+      - name: Check out repository code
         uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by wget
+      - name: Run commands inside the Docker container
         run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf /usr/bin/curl # remove curl
-            yum install -y wget
-            rm -rf * .??*
-            wget -O- ${INSTALLATION_URL} | sh
-            ls -ahl
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 1
-          echo "PASS"
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a failed download by wget
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf /usr/bin/curl # remove curl
-            command -v "wget"
-            [ -f /usr/bin/wget ] && rm -f /usr/bin/wget
-            rm -rf * .??*
-            wget -O- ${INSTALLATION_URL} | sh
-            ls -ahl
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] || exit 1
-          echo "PASS"
-
-  git_download_on_centOS:
-    runs-on: ubuntu-latest
-    name: wget download on CentOS
-    strategy:
-      matrix:
-        centos: [ 'centos:centos8.4.2105', 'centos:centos8' ]
-    env:
-      CENTOS_VERSION: ${{ matrix.centos }}
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by wget
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${CENTOS_VERSION} bash -c "
-            cd /etc/yum.repos.d/ && rm -rf * .??* && cd -
-            cat .github/workflows/CentOS-Base.repo > /etc/yum.repos.d/CentOS-Base.repo
-            cat /etc/yum.repos.d/CentOS-Base.repo
-            rm -rf /usr/bin/curl # remove curl
-            yum install -y git
-            rm -rf * .??*
-            git clone --branch ${GIT_VERSION} --single-branch --recurse-submodules ${GIT_REP_URL} && cd dotfiles
-            ls -ahl
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] && exit 1
-          echo "PASS"
-
-  curl_download_on_macOS_x86:
-    runs-on: macos-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by curl
-        run: |
-          curl -fsSL ${INSTALLATION_URL} | sh
-
-  wget_download_on_macOS_x86:
-    runs-on: macos-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by wget
-        run: |
-          wget -O- ${INSTALLATION_URL} | sh
-  git_download_on_macOS_x86:
-    runs-on: macos-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      - name: Asserting the result of a successful download by git
-        run: |
-          git clone --branch ${GIT_VERSION} --single-branch --recurse-submodules ${GIT_REP_URL} && cd dotfiles
+          node --version
+          npm --version
