chore(install script): update install script #104

diff --git a/.github/workflows/install_script_test.yaml b/.github/workflows/install_script_test.yaml
--- a/.github/workflows/install_script_test.yaml
+++ b/.github/workflows/install_script_test.yaml
@@ -246,10 +246,6 @@ jobs:
 #          [ "${lsCount}" -eq 0 ] && exit 1
 #          printf "${SUCCESSFUL_LOG}"
 #
-#
-#
-#
-#
 #  git_on_centOS:
 #    needs:
 #      - setup_matrix_for_centOS
@@ -321,40 +317,40 @@ jobs:
       - id: set-matrix
         run: echo 'matrix=["ubuntu:23.10"]' >> $GITHUB_OUTPUT
 
-  curl_on_ubuntu:
-    needs:
-      - setup_matrix_for_ubuntuOS
-    name: Curl on ubuntu
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
-    env:
-      UBUNTU_IMAGE_VERSION: ${{ matrix.image}}
-
-    steps:
-      - name: Successful curl download on ubuntu
-        run: |
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            apt update;
-            apt install -y curl;
-            curl -fsSL ${INSTALLATION_URL} | bash;
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -gt 0 ] || exit 1
-          printf "${SUCCESSFUL_LOG}"
-      - name: Failed curl download on ubuntu
-        run: |
-          rm -rf * .??*
-          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            curl -fsSL ${INSTALLATION_URL} | bash;
-          "
-          lsCount=$(ls dotfiles/ | wc -c)
-          echo "ls count: ${lsCount}"
-          [ "${lsCount}" -eq 0 ] || exit 1
-          printf "${SUCCESSFUL_LOG}"
+#  curl_on_ubuntu:
+#    needs:
+#      - setup_matrix_for_ubuntuOS
+#    name: Curl on ubuntu
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+#    env:
+#      UBUNTU_IMAGE_VERSION: ${{ matrix.image}}
+#
+#    steps:
+#      - name: Successful curl download on ubuntu
+#        run: |
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            apt update;
+#            apt install -y curl;
+#            curl -fsSL ${INSTALLATION_URL} | bash;
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -gt 0 ] || exit 1
+#          printf "${SUCCESSFUL_LOG}"
+#      - name: Failed curl download on ubuntu
+#        run: |
+#          rm -rf * .??*
+#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+#            curl -fsSL ${INSTALLATION_URL} | bash;
+#          "
+#          lsCount=$(ls dotfiles/ | wc -c)
+#          echo "ls count: ${lsCount}"
+#          [ "${lsCount}" -eq 0 ] || exit 1
+#          printf "${SUCCESSFUL_LOG}"
 
 #  curl_tar_on_ubuntu:
 #    needs:
@@ -393,6 +389,7 @@ jobs:
 #          printf "${SUCCESSFUL_LOG}"
 #
 #
+
   curl_unzip_on_ubuntu:
     needs:
       - curl_on_ubuntu
@@ -419,45 +416,65 @@ jobs:
           echo "ls count: ${lsCount}"
           [ "${lsCount}" -gt 0 ] || exit 1
           printf "${SUCCESSFUL_LOG}"
-      - name: Failed curl download on ubuntu
+
+
+  wget_on_ubuntu:
+    name: Wget on ubuntu
+    needs:
+      - setup_matrix_for_ubuntuOS
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+    env:
+      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
+
+    steps:
+      - name: Successful wget download on ubuntu
+        run: |
+          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+            apt update;
+            apt install -y wget;
+            wget -O- ${INSTALLATION_URL} | bash
+          "
+          lsCount=$(ls dotfiles/ | wc -c)
+          echo "ls count: ${lsCount}"
+          [ "${lsCount}" -gt 0 ] || exit 1
+          echo "${SUCCESSFUL_LOG}"
+      - name: Failed wget download on ubuntu
         run: |
           rm -rf * .??*
           docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-            curl -fsSL ${INSTALLATION_URL} | bash;
+            apt update;
+            wget -O- ${INSTALLATION_URL} | bash
           "
           lsCount=$(ls dotfiles/ | wc -c)
           echo "ls count: ${lsCount}"
           [ "${lsCount}" -eq 0 ] || exit 1
-          printf "${SUCCESSFUL_LOG}"
-#
-#  wget_download_on_ubuntu:
-#    name: wget download on ubuntu
-#    runs-on: ubuntu-latest
-#    strategy:
-#      matrix:
-#        image: [ 'ubuntu:23.10']
-#    env:
-#      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
-#
-#    steps:
-#      - name: Successful wget download on ubuntu
-#        run: |
-#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-#            apt update;
-#            apt install -y wget;
-#            wget -O- ${INSTALLATION_URL} | bash
-#          "
-#          lsCount=$(ls dotfiles/ | wc -c)
-#          echo "ls count: ${lsCount}"
-#          [ "${lsCount}" -gt 0 ] || exit 1
-#          echo "${SUCCESSFUL_LOG}"
-#      - name: Failed wget download on ubuntu
-#        run: |
-#          rm -rf * .??*
-#          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
-#            apt update;
-#            wget -O- ${INSTALLATION_URL} | bash
-#          "
-#          lsCount=$(ls dotfiles/ | wc -c)
-#          echo "ls count: ${lsCount}"
-#          [ "${lsCount}" -eq 0 ] || exit 1
+
+  wget_tar_on_ubuntu:
+    name: Wget->tar on ubuntu
+    needs:
+      - setup_matrix_for_ubuntuOS
+      - wget_on_ubuntu
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        image: ${{fromJson(needs.setup_matrix_for_ubuntuOS.outputs.matrix)}}
+    env:
+      UBUNTU_IMAGE_VERSION: ${{ matrix.image }}
+
+    steps:
+      - name: Successful wget download on ubuntu
+        run: |
+          docker run --rm -v $PWD:/workdir -w /workdir ${UBUNTU_IMAGE_VERSION} bash -c "
+            apt update;
+            apt install -y wget tar;
+            wget -O- ${INSTALLATION_URL} | bash
+          "
+          lsCount=$(ls dotfiles/ | wc -c)
+          echo "ls count: ${lsCount}"
+          [ "${lsCount}" -gt 0 ] || exit 1
+          echo "${SUCCESSFUL_LOG}"
